#!/bin/bash
cd Person
. ./person
cd ..
MOUNY=$MOUNY
function armorshop {
 echo -e "Вы входите в лавку с бронёй на вывеске\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "За прилавком сидит мужик боготырского вида\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продовец: Здаров, чего тебе\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Вы: Да так, осмотреться хочу\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продавец: Ну смотри, кто ж тебе не даёт, но деньги то у тебя есть\r\c"
 if [ $MOUNY == 0 ]; then
   echo -e "Вы: Не, мужик, я на мели\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну чего ты так\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Да вот не знаю, где можно деньгами разжиться, может, подскажешь?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну ты чего, совсем что-ли, иди в подземелье, тут недалеко, там можно много чего найти\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Хорошо\r\c"
   sleep 5
   echo -e "\033[K\c"
  else
   echo "Вы: Да, есть, дашь теперь глянуть?"
   echo "Продовец: Ну вот, смотри"
   cat Tread_Prises/armor
   cat Tread_Prises/headarmor
 fi
}
function weponshop {
 echo -e "Вы входите в лавку с мечём на вывеске\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "За прилавком сидит мужик небольщого роста, но при этом крайне широкоплечий\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продовец: Здаров, чего тебе\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Вы: Да так, осмотреться хочу\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продавец: Ну смотри, кто ж тебе не даёт, но деньги то у тебя есть\r\c"
 if [ $MOUNY == 0 ]; then
   echo -e "Вы: Не, мужик, я на мели\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну чего ты так\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Да вот не знаю, где можно деньгами разжиться, может, подскажешь?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну ты чего, совсем что-ли, иди в подземелье, тут недалеко, там можно много чего найти\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Хорошо\r\c"
   sleep 5
   echo -e "\033[K\c"
  else
   echo "Вы: Да, есть, дашь теперь глянуть?"
   echo "Продовец: Ну вот, смотри"
   cat Tread_Prises/weapon
 fi
}
function poisonshop {
 echo -e "Вы входите в лавку с бутыльком на вывеске\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "За прилавком сидит бабка неопределённого возроста и комплекции\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продовец: Здаров, чего тебе\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Вы: Да так, осмотреться хочу\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Продавец: Ну смотри, кто ж тебе не даёт, но деньги то у тебя есть\r\c"
 sleep 5
 echo -e "\033[K\c"
 if [ $MOUNY == 0 ]; then
   echo -e "Вы: Не, бабушка, я на мели\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну чего ты так\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Да вот не знаю, где можно деньгами разжиться, может, подскажешь?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Продовец: Ну ты чего, совсем что-ли, иди в подземелье, тут недалеко, там можно много чего найти\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Хорошо\r\c"
   sleep 5
   echo -e "\033[K\c"
  else
   echo "Вы: Да, есть, дашь теперь глянуть?"
   echo "Продовец: Ну вот, смотри"
   cat Tread_Prises/poison
 fi
}
cat Frames/start.txt
MOUNY=0
echo ""
echo "Добро пожаловать в игру, введите имя:"
read -r name
echo -e "\033[3A"
sleep 5
echo -e "\033[K\c"
sed -r -i.bak "s/name=([[:graph:]]+)/name=$name/" Person/person
echo "Вы находитесь на рыночке небольшого городка"
echo "Рядом с вами находится несколько торговых лавок"
echo "Выберите вариант:"
echo "1 - Подойти к лавке с мечём на вывеске"
echo "2 - Подойти к лавке с бронёй на вывеске"
echo "3 - Подойти к лавке с бутыльком на вывеске"
read -r C
echo -e "\033[8A"
sleep 5
tput ed
if (( $C == 1 )); then
  armorshop
elif (( $C == 2 )); then
  weponshop
elif (( $C == 3 )); then
  poisonshop

fi
echo "Вы выходите из лавки"
sed -r -i.bac 's/MOUNY([[:graph:]]+)/MOUNY=$MOUNY/' Person/person
. ./Menu
#echo "Для того, чтобы пойти в подземелье, введите Dangon"
#echo "Для того, чтобы посмотреть состояние персонажа, введите viperson"
#read -r C1
#case $C1 in
# Dangon)
# . ./Dangon;;
# viperson)
# . ./viperson;;
#esac
