#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/qwests/ratter/main_rattrer.txt
echo ""
echo -e "Вы возврашаетесь к башне крысоловов\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы входите в башню крысоловов\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Главный крысолов: Ну как успехи?\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Вы: Есть успехи?\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Главный крысолов: И что за успехи?\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Вы: Да увидел какие-то стрнанны е знакив коллекторах, подумал, может вам интересно будет\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Главный крысолов: Отлично, сможешь указать на карте?\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Вы: Думаю да, если карту дадите\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Главный крысолов: Отлично, вот карта, показывай\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Вы указываете примерное место, где вы видели символы\r\c"
sleep 5
echo -e "\033K\c"
echo -e "Главный крысолов: Отлично, мои парни сходят, осмотрят, вот твоя награда, если ещё что-то понадобится, мы тебя найдём\r\c"
sleep 5
echo -e "\033K\c"
let MOUNY=$MOUNY+100
sed -r -i.bac 's/MOUNY([[:graph:]]+)/MOUNY=$MOUNY/' ../../Person/person
cd ../..
./Menu