#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/qwests/hanter/hanter.txt
echo ""
echo -e "Вы подходите к лавке охотника\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "На крыльце сидит транного вида человек со слегка заострёнными ушами\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Чё надо?\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы: Да вот, увидел объявление, ну и пришёл\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Раз уж пришёл, смотри, какое дело к тебе есть, нужно оленя выследить\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы: И где начать его искать\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: К реке сходи, она на заподе отсюда, туда всё местное зверьё на водопой ходит\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Отправиться к реке"
echo -e "2 - Вернуться в город"
read -r C
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы: Хорошо, схожу, посмотрим, что я смогу сделать\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Хорошо, жду\r\c"
 sleep 5
 echo -e "\033[K\c"
 qwest_chein_progress[0]=1
 sed -r -i.bac "s/qwest_chein_progress[0]([[:graph:]]+)/qwest_chein_progress[0]=${qwest_chein_progress[0]}/" ../../Person/person
 . ./riwer1
;;
2)
 echo -e "Вы: Не, как нибудь в другой раз\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Как хочешь"
 sleep 5
 echo -e "\033[K\c"
 cd ../..
 . ./Menu
;;
esac
