#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/market/qwests/hanter/hanter.txt
echo ""
echo -e "Вы просыпаетесь\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы выходите на улицу\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "На крыльце сидит охотник и перебирает принесённыё вами камушки\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Ну как, выспался\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы: Да, что там за задание на сегодня?\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Значит смотри, идёшь к реке, где она ты знаещь\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Как дойдёшь, поворачивай на юг и иди пока не увидишь свечение на горизонте\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Идёшь на это свечение, там будет роща деревьев с белой корой\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Так вот, выруби мне какое-нибудь молодое деревце\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Только будь осторожен, я туда давно не ходил, не знаю, что там завелось\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Отправиться в рощу"
echo -e "2 - Вернуться в город"
read -r C
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы: Хорошо, схожу, посмотрим, что я смогу сделать\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Хорошо, жду\r\c"
 sleep 5
 echo -e "\033[K\c"
 . ./riwer1
;;
2)
 echo -e "Вы: Не, как нибудь в другой раз\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Как хочешь"
 sleep 5
 echo -e "\033[K\c"
 cd ../..
 . ./Menu
;;
esac

sed -r -i.bac "s/qwest_chein_progress[0]([[:graph:]]+)/qwest_chein_progress[0]=${qwest_chein_progress[0]}/" person
