#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/qwests/hanter/magic_forest.txt
echo ""
echo -e "Вы выходите к роще\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вокруг ростут деревья с белой корой, которая немного светится\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Осмотреться"
echo -e "2 - Вернуться в город"
read -r C
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы осматриваетесь\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "\r\c"
 sleep 5
 echo -e "\033[K\c"
 clear
 cat ../../Frames/qwests/hanter/little_tree.txt
 echo -e "Недалеко от вас вы видите молодое и давольно ровное деревце\r\c"
 sleep 5
 echo -e "\033[K\c" 
 echo -e "Выберите вариант:"
 echo -e "1 - Осмотреть дерево"
 echo -e "2 - Вернуться в город"
 read -r C
 echo -e "\033[5A"
 tput ed
 case $C in
  1)
   clear
   cat ../../Frames/qwests/hanter/feary.txt
   echo -e "Вы осматриваете деревце\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Под деревцем вы замечаете маленькое существо, похожее на девушку \r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Здравствуй, ты кто?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Существо: Ой, здравствуйте, а вы человек?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Да, человек, а ты то кто?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Существо: Я... я феари... правда неправильная...\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: В каком смысле неправильная?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: Я... я покинула своё дерево, а так нельзя... А вы правда человек?\r\c"
   sleep 5
   echo -e "\033[K\c\r\c"
   echo -e "Вы: Ну да, а что?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: Я никогда не видела людей... А что вы тут делаете?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Я? Да мне вот, дерево нужно\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: А, а зачем вам?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Понятия не имею, меня охотник попросил\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: А... всё... поняла... Ну, если вам нужно дерево, берите это, тут вроде дриады нет\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Хорошо\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы срубаете деревце\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Фух, всё. Ладно, бывай\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: А... И-извините...\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Вы: Что такое?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Феари: А... м-можно мне с вами пойти?\r\c"
   sleep 5
   echo -e "\033[K\c"
   echo -e "Выберите вариант:"
   echo -e "1 - Да, почему бы и нет"
   echo -e "2 - Не, прости"
   read -r C
   echo -e "\033[5A"
   tput ed
   case $C in
   1)
    echo -e "\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Вы: Да, почему бы и нет\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Феари: Ураааа!!\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Феари на радостях начала летать вокруг вас, после чего влетела к вам в сумку\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Вы подхватываете деревце и идёте к охотнику\r\c"
    sleep 5
    echo -e "\033[K\c"
    let feary=$feary+1
    sed -r -i.bac 's/feary([[:graph:]]+)/feary=$feary/' ../../Person/person
    . ./win_of_qwest
   ;;
   2)
    echo -e "Вы: Не, звиняй, конечно, но у меня не получится тебя с собой взять\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Феари: А... ну... простите... и... пощайте\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Понурившаяся феари улетает прочь\r\c"
    sleep 5
    echo -e "\033[K\c"
    echo -e "Вы подхватываете деревце и идёте к охотнику\r\c"
    sleep 5
    echo -e "\033[K\c"
    . ./win_of_qwest
   ;;
  ;;
  2)
   cd ../..
   . ./Menu
  ;;
 esac
;;
2)
 cd ../..
 . ./Menu
;;
esac
