#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/qwests/hanter/river.txt
echo ""
echo -e "Вы выходите к реке\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Перед вами открывается вид на тихую заводь вокруг которой ростут заросли кустарника\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Осмотреться"
echo -e "2 - Вернуться в город"
read -r C
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы осматриваетесь\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "На берегу вы замечате следы, очень похожие на оленьи\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Следы выглядят давольно свежими\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "\033[K\c"
 echo -e "Выберите вариант:"
 echo -e "1 - Пойти по следу"
 echo -e "2 - Вернуться в город"
 read -r C
 echo -e "\033[5A"
 tput ed
 case $C in
  1)
   echo -e "Вы идёте по следу\r\c"
   sleep 5
   echo -e "\033[K\c"
   . ./deer_hant
  ;;
  2)
   cd ../..
   . ./Menu
  ;;
 esac
;;
2)
 cd ../..
 . ./Menu
;;
esac
