#!/bin/bash
cd ../../Person
. ./person
. ./person_armor
. ./person_headarmor
cd ../Qwests/Hanter
clear
cat ../../Frames/qwests/hanter/hanter.txt
let qwest_chein_progress[0]=${qwest_chein_progress[0]}++
sed -r -i.bac "s/qwest_chein_progress[0]([[:graph:]]+)/qwest_chein_progress[0]=${qwest_chein_progress[0]}/" ../../Person/person
echo ""
echo -e "Вы возваращаетесь к охотнику\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Охотник: Как успехи?\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Вы: Отлично, вот добыча\r\c"
sleep 5
echo -e "\033[K\c"
case ${qwest_chein_progress[0]} in
1)
;;
2)
 a=$(awk '/Тушка_грипа/{ print NR }' ../../Person/inventary)
 my=`sed -n "${a}p"  ../../Person/inventary`
 arrb=($my)
 let arrb[1]=${arrb[1]}-10
 d="${arrb[0]} ${arrb[1]}"
 if ((${arrb[1]} > 10)); then
  sed -i "${a}c\ $d" ../../Person/inventary
 else
  sed --in-plase "${a} d" ../../Person/inventary
;;
2)
 a=$(awk '/Белый_самоцвет/{ print NR }' ../../Person/inventary)
 my=`sed -n "${a}p"  ../../Person/inventary`
 arrb=($my)
 let arrb[1]=${arrb[1]}-10
 d="${arrb[0]} ${arrb[1]}"
 if ((${arrb[1]} > 10)); then
  sed -i "${a}c\ $d" ../../Person/inventary
 else
  sed --in-plase "${a} d" ../../Person/inventary
;;
esac
echo -e "Охотник: Ну что теперь будешь делать\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Что дальше делать?"
echo -e "2 - Вернуться в город"
read -r C
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы: Что дальше делать?\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Отдахни, у меня на чердаке место спальное есть\r\c"
 sleep 5
 echo -e "\033[K\c"
 . ./hanter${qwest_chein_progress[0]}
;;
2)
 echo -e "Вы: Схожу в город, может, прикуплю что-нибудь\r\c"
 sleep 5
 echo -e "\033[K\c"
 echo -e "Охотник: Как хочешь"
 sleep 5
 echo -e "\033[K\c"
 cd ../..
 . ./Menu
;;
esac