#!/bin/bash
. ./person
. ./person_weapon
clear
cat ../../Frames/plate/plate.txt
echo ""
echo -e "Вы гуляете по городу\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "У одного из зданий стоит доска с приколотыми к ней листами пергамента\r\c"
sleep 5
echo -e "\033[K\c"
echo -e "Выберите вариант:"
echo -e "1 - Подойти к доске объявлений"
echo -e "2 - Продолжить прогулку по городу"
read -r C
sleep 5
echo -e "\033[5A"
tput ed
case $C in
1)
 echo -e "Вы подхлдите к доске объявлений\r\c"
 sleep 5
 echo -e "\033[K\c"
 while true; do
 echo -e "Выберите вариант:"
 echo -e "1 - Пойти к охотнику"
 echo -e "2 - Пойти в башню крысоловов"
 echo -e "3 - Продолжить прогулку по городу" 
 read -r C
 case $C in
  1)
   case ${qwest_chein_progress[0]} in
   0)
    . ../../Qwests/Hanter/hanter1
   ;;
   1 | 2 | 3 | 4)
    . ../../Qwests/Hanter/hanter${qwest_chein_progress[0]} 
   ;;
   5)
    echo -e "Вы заканчили с охотником\r\c"
    sleep 5
    echo -e "\033[K\c"
   ;;
 done
  ;;
 esac
;;
2)
 . ../../Qwests/Ratter/ratter
;;
3)
 cd ../..
 . ./Menu
;;
esac
